import { Puzzle } from "/Users/colinmack/Documents/Developer/crossword-app/src/app/puzzle"

export const PUZZLES: Puzzle[] = [
	{ 
		id: 1, 
		title: "Colin's First Crossword" ,
		date: "Jun. 25, 2021",
		grid: [
			["#","#","R","A","C","E"],
			["#","C","U","R","L","S"],
			["#","O","N","T","A","P"],
			["M","U","N","I","S","#"],
			["A","P","I","S","H","#"],
			["R","E","N","T","#","#"]
		],
		acrossClues: [
			"Something Colin will participate in, on November 7th",
			"Exercises with dumbbells",
			"Where one might find a Sierra Nevada at a San Francisco bar",
			"San Francisco buses, familiarly",
			"Monkey-like?",
			"Monthly cost for apartment living"
		],
		downClues: [
			"What Colin will be doin' on November 7th",
			"What one might call themselves after designing a mini crossword puzzle",
			"Colors that don't go well together are said to do this",
			"Sixth-sense",
			"Car like a Mustang or Camaro?",
			"Mon. before Colin's birthday"
		]
	},
	{ 
		id: 2, 
		title: "Just for Kicks", 
		date: "Jun. 30, 2021",
		grid: [
			["#","#","#","S","P","F","#","#"],
			["#","#","S","A","L","A","D","#"],
			["#","F","A","N","A","T","I","C"],
			["H","O","V","#","N","I","K","E"],
			["I","R","A","S","#","G","E","O"],
			["P","E","G","A","S","U","S","#"],
			["#","S","E","G","U","E","#","#"],
			["#","#","D","E","N","#","#","#"]
		],
		acrossClues: [
			"Val. for protection from 14-Down",
			"Caesar, for example",
			"Swiftie, Belieber, or... Mackinator? Open to suggestions",
			"Carpool lane letters",
			"With 13-Across, Colin's training shoe of choice",
			"Retirement account options",
			"Prefix with 'thermal'",
			"See 9-Across",
			"Transition",
			"Lair"
		],
		downClues: [
			"Part of SF",
			"Prepare",
			"Post-marathon feeling",
			"Viciously attacked",
			"Flood protection walls",
			"Golf course yells",
			"Bus. boss",
			"Target of a pretzel stretch",
			"Arromatic plant",
			"See 1-Across"
		]
	},
	{ 
		id: 3, 
		title: "City Guides", 
		date: "Sept. 5, 2021", 
		grid: [
			["P.","R.","E.","V","#","M.","A.","R.","A","C","A","S"],
			["S.","I.","D.","E","#","I.","N.","A.","R","A","G","E"],
			["I.","O.","U","S","#","N","O","I","S","I","E","R"],
			["#","#","#","S","A","O","#","S","E","N","S","E"],
			["R","E","H","E","A","R","S","E","#","#","#","#"],
			["N","A","I","L","S","I","T","#","S.","O.","M.","A."],
			["A","R","M","S","#","T","U","N","E","S","U","P"],
			["#","#","#","#","S","Y","N","D","R","O","M","E"],
			["S","F","M","A","P","#","N","A","V","#","#","#"],
			["A","L","A","M","O","D","E","#","A","M.","I.","S."],
			["S.","U.","N.","N","I","E","R","#","N","I","S.","I."],
			["S.","E.","T.","T","L","E","S","#","T","O","O.","N."]
		],
		acrossClues: [
			"\"Go Back\" button abbr. on some remotes",
			"Musical shakers",
			"_____ by _____",
			"Furious",
			"Debts: Abbr.",
			"More boisterous",
			"Saint of Lisbon",
			"Taste or touch, for example",
			"Practice for performance",
			"Does a great job",
			"Eurphoric drug in Brave New World",
			"Activates, as a security alarm",
			"Brings to a pitch",
			"Stockholm, for example",
			"U.S. atlas image represented by this puzzle.",
			"Maritime org.",
			"Pie order specification",
			"Friends in Paris",
			"More gleaming",
			"Not final, in law",
			"Resolves",
			"Animated character"
		],
		downClues: [
			"Follower of Chi",
			"River of Rome",
			"Campus URL ending",
			"Blood lines",
			"Lesser group",
			"Year of Madrid",
			"Increase in salary",
			"Seat of London",
			"Biblical brother",
			"Historic periods",
			"Dry",
			"Some batteries",
			"Genetic letters",
			"Corn unit",
			"He/_____/His",
			"Amazing feats",
			"Minion",
			"Bear in Barcelona",
			"Silent",
			"Monkey",
			"Contract to protect private info",
			"Go bad",
			"Back talk",
			"Chimney passage",
			"Creole breath freshener",
			"Cousin of ain't",
			"Sandra referenced in a Grease song.",
			"\"Ay, dios ____!\"",
			"Prefix with late or metric",
			"Wrong doing"
		]
	},
	{ 
		id: 4, 
		title: "Just an Observation", 
		date: "Jan. 26, 2022", 
		grid: [
			["S","T","A","N","D","#","B","O","B","A","#","R","I","F","F","S"],
			["T","R","O","L","L","#","E","N","O","S","#","A","V","E","R","T"],
			["R","A","R","E","S","#","E","T","A","L","#","V","E","N","U","E"],
			["E","S","T","#","#","O","C","H","R","E","S","#","#","D","I","P"],
			["W","H","A","T","S","T","H","E","D","E","A","L","W","I","T","H"],
			["#","#","#","R","E","S","T","#","#","P","L","E","A","#","#","#"],
			["T","A","R","O","T","#","R","O","E","#","U","N","I","S","O","N"],
			["A","T","O","M","#","R","E","N","E","S","T","#","T","E","R","I"],
			["B","O","M","B","#","H","E","C","K","L","E","#","H","A","C","K"],
			["S","N","O","O","T","Y","#","E","S","E","#","D","E","N","S","E"],
			["#","#","#","N","A","M","E","#","#","U","B","E","R","#","#","#"],
			["Y","O","U","E","V","E","R","N","O","T","I","C","E","H","O","W"],
			["E","L","S","#","#","S","O","U","G","H","T","#","#","A","P","R"],
			["A","D","I","E","U","#","D","E","L","I","#","F","E","S","T","A"],
			["R","I","N","D","S","#","E","V","E","N","#","T","R","A","I","T"],
			["S","E","G","U","E","#","S","E","R","G","#","C","A","T","C","H"]
		],
		acrossClues: [
			"Comic's stage performance, with 'up'",
			"Tea with tapioca balls, familiarly",
			"Comic's improvisations",
			"Online instigator",
			"Genesis grandson",
			"Skirt",
			"Some steak orders?",
			"And others: Abbr.",
			"New York's Comedy Cellar, for one",
			"NY time",
			"Earthy tones",
			"Counterpart to chips",
			"Opening for a comic's observation",
			"Take it easy",
			"Court statement",
			"Kind of card",
			"____ v. Wade",
			"Harmony",
			"Particle",
			"Make a new home, say",
			"Comedian Garr",
			"Fail miserably, for a comic",
			"Pester, for a comic",
			"One considered trite, for a comic",
			"High and mighty",
			"Language suffix",
			"Tightly packed",
			"'Chris Rock' or 'Jerry Seinfeld'",
			"App for a lift",
			"Opening for a comic's observation",
			"Trains near Second City",
			"Pursued",
			"Loan val.",
			"French farewell",
			"Katz's, for example",
			"Party in Rome",
			"Typical watermelon discards",
			"Equal",
			"Attribute",
			"Comic's transition",
			"N.C.O.",
			"Comic's preceeder of phrase"
		],
		downClues: [
			"Scatter",
			"Rubbish",
			"Main artery",
			"Div. for the Mets and Marlins",
			"MLB injured reserves",
			"Possible source of fire wood",
			"Words before rocks, in a drink order",
			"Get on, as a plane",
			"Inactive",
			"4 offering from Toyota",
			"'Now ____ seen everything!'",
			"Gucci rival",
			"Type of salad",
			"2-time NBA MVP Curry",
			"Extra periods after a game-tying score",
			"Greeting for 78-Across",
			"Big brass",
			"Comic's show",
			"'Dancing with the Stars' judge Goodman",
			"'Don't move!'",
			"Chrome dividers",
			"Heaps",
			"CBS Football Commentator Tony",
			"Singly",
			"Shrieks",
			"Penn, for example",
			"Tolkien monsters",
			"Air Force brand?",
			"Poetic pairs",
			"Internet stalking, for example",
			"Last Hebrew letter",
			"Last mon.",
			"Wears away",
			"Comic's routine",
			"Laps around the sun",
			"Bygone song",
			"Gerund of 70-Down",
			"Number one more than ocho",
			"Rude looker",
			"Goes after",
			"Related to the eyes",
			"Fury",
			"University website ending",
			"See 59-Down",
			"Antitrust org.",
			"Pitcher's stat"
		]
	}
];